# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8VoACoXz2lP_wfkWhv58XaW_otwhiUu
"""

def kasallik_tashxisi(belgi):
   if belgi=="Bosh og'rig'i":
       return "Bolnol iching"
   elif belgi=="Qorin og'rig'i":
       return"Espumizan iching"

   elif belgi=="Tish og'rig'i":
       return "Qupen iching"
   else:
        return "Shifokorga murojaat qiling"
belgi=input("Kasallik belgisini kiriting")
natija=kasallik_tashxisi(belgi)
print(natija)

def Avtobus_qatnovi(belgi):
  if belgi=="Dehqon bozorga borish":
     return "12-Avtobusga chiqing"
  elif belgi=="Markazga borish":
      return"10-Avtobusga chiqing"
  elif belgi=="Tefefon markazga borish":
      return "2-Avtobusga chiqing"
  elif belgi=="Avtovakzalga borish":
      return "7-Avtobusga chiqing"
  elif belgi=="Vokzalga borish":
      return "8-Avtobusga chiqing"
  elif belgi=="Airaportga borish":
      return "3-Avtobusga chiqing"
  elif belgi=="Masjidga borish":
      return "1-Avtobusga chiqing"
  elif belgi=="Kiyim Markazga borish":
      return "9-Avtobusga chiqing"
  elif belgi=="Korzinkaga borish":
      return "20-Avtobusga chiqing"
  else:
      return "BU JOYGA AVTOBUS QATNOVI MAVJUD EMAS!"
belgi=input("Qayerga borishingizni kiriting")
natija=Avtobus_qatnovi(belgi)
print(natija)